import json
import io
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import queue
import asyncio
from contextlib import asynccontextmanager
from typing import List, Dict, Optional

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Request, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from dotenv import load_dotenv
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from sqlalchemy.orm import Session as DBSessionORM

from agents.tutor import MultiAgentCouncil
from knowledge.rag import init_knowledge_base
from knowledge.learning_paths import LEARNING_PATH, get_module_by_id
from database import init_db, get_db, DBSession, DBSessionFile, DBChatMessage, DBSnapshot

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EXECUTION_TIMEOUT_SECONDS = 10
DOCKER_IMAGE = "python:3.11-slim"
PLOT_MARKER = "__OASIS_PLOT__:"

# Prepended to main.py: patches plt.show() to emit a base64 PNG marker
MATPLOTLIB_PREAMBLE = """\
import io as __oasis_io, base64 as __oasis_b64
try:
    import matplotlib as __oasis_mpl; __oasis_mpl.use('Agg')
    import matplotlib.pyplot as __oasis_plt
    def __oasis_show(*a, **kw):
        buf = __oasis_io.BytesIO()
        __oasis_plt.savefig(buf, format='png', bbox_inches='tight', dpi=100)
        buf.seek(0)
        print(f\"{PLOT_MARKER}{{__oasis_b64.b64encode(buf.read()).decode()}}\", flush=True)
        __oasis_plt.close('all')
    __oasis_plt.show = __oasis_show
except ImportError:
    pass
"""

# ---------------------------------------------------------------------------
# Docker availability check
# ---------------------------------------------------------------------------

DOCKER_AVAILABLE = False


def _check_docker() -> None:
    global DOCKER_AVAILABLE
    try:
        import docker  # noqa: PLC0415
        client = docker.from_env(timeout=5)
        client.ping()
        try:
            client.images.get(DOCKER_IMAGE)
        except Exception:
            log.info("Pulling Docker image %s ...", DOCKER_IMAGE)
            client.images.pull(DOCKER_IMAGE)
        DOCKER_AVAILABLE = True
        log.info("Docker sandbox ready.")
    except Exception as e:
        log.warning("Docker unavailable — using subprocess sandbox: %s", e)


# ---------------------------------------------------------------------------
# App lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("Startup: initialising knowledge base, database and checking Docker...")
    await asyncio.to_thread(init_knowledge_base)
    await asyncio.to_thread(_check_docker)
    await asyncio.to_thread(init_db)
    yield
    log.info("Shutdown.")


# ---------------------------------------------------------------------------
# App and middleware
# ---------------------------------------------------------------------------

limiter = Limiter(key_func=get_remote_address)
app = FastAPI(title="Oasis: Multi-Agent Lab Backend", lifespan=lifespan)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

allowed_origins = os.environ.get("ALLOWED_ORIGINS", "http://localhost:3000").split(",")
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

council = MultiAgentCouncil()


# ---------------------------------------------------------------------------
# Curriculum endpoint
# ---------------------------------------------------------------------------

@app.get("/api/curriculum")
async def get_curriculum():
    return LEARNING_PATH


# ---------------------------------------------------------------------------
# Session persistence endpoints
# ---------------------------------------------------------------------------

class SessionCreateRequest(BaseModel):
    id: str  # UUID generated by client
    display_name: Optional[str] = None
    provider: str = "openai"
    active_module_index: int = 0
    milestone: str = "API Basics & Prompting"
    active_file_name: str = "main.py"


class SessionMetaPatch(BaseModel):
    display_name: Optional[str] = None
    provider: Optional[str] = None
    active_module_index: Optional[int] = None
    milestone: Optional[str] = None
    active_file_name: Optional[str] = None


class FilesPayload(BaseModel):
    files: List[Dict[str, str]]  # [{name, content}]


class MessagesPayload(BaseModel):
    messages: List[Dict[str, object]]  # [{role, content, seq}]


def _session_to_dict(session: DBSession) -> dict:
    return {
        "id": session.id,
        "display_name": session.display_name,
        "provider": session.provider,
        "active_module_index": session.active_module_index,
        "milestone": session.milestone,
        "active_file_name": session.active_file_name,
        "created_at": session.created_at.isoformat() if session.created_at else None,
        "updated_at": session.updated_at.isoformat() if session.updated_at else None,
        "files": [{"name": f.name, "content": f.content} for f in session.files],
        "messages": [{"role": m.role, "content": m.content, "seq": m.seq} for m in session.messages],
    }


@app.post("/api/sessions", status_code=201)
def create_session(body: SessionCreateRequest, db: DBSessionORM = Depends(get_db)):
    existing = db.get(DBSession, body.id)
    if existing:
        return _session_to_dict(existing)
    session = DBSession(
        id=body.id,
        display_name=body.display_name,
        provider=body.provider,
        active_module_index=body.active_module_index,
        milestone=body.milestone,
        active_file_name=body.active_file_name,
    )
    db.add(session)
    db.commit()
    db.refresh(session)
    return _session_to_dict(session)


@app.get("/api/sessions/{session_id}")
def get_session(session_id: str, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return _session_to_dict(session)


@app.patch("/api/sessions/{session_id}")
def patch_session(session_id: str, body: SessionMetaPatch, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if body.display_name is not None:
        session.display_name = body.display_name
    if body.provider is not None:
        session.provider = body.provider
    if body.active_module_index is not None:
        session.active_module_index = body.active_module_index
    if body.milestone is not None:
        session.milestone = body.milestone
    if body.active_file_name is not None:
        session.active_file_name = body.active_file_name
    db.commit()
    return {"ok": True}


@app.put("/api/sessions/{session_id}/files")
def upsert_files(session_id: str, body: FilesPayload, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    incoming_names = {f["name"] for f in body.files}
    # Remove files that no longer exist
    for existing_file in list(session.files):
        if existing_file.name not in incoming_names:
            db.delete(existing_file)
    # Upsert
    existing_map = {f.name: f for f in session.files}
    for file_data in body.files:
        name = file_data["name"]
        content = file_data.get("content", "")
        if name in existing_map:
            existing_map[name].content = content
        else:
            db.add(DBSessionFile(session_id=session_id, name=name, content=content))
    db.commit()
    return {"ok": True}


@app.post("/api/sessions/{session_id}/messages")
def upsert_messages(session_id: str, body: MessagesPayload, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    existing_seqs = {m.seq for m in session.messages}
    for msg in body.messages:
        seq = int(msg["seq"])
        if seq not in existing_seqs:
            db.add(DBChatMessage(
                session_id=session_id,
                role=str(msg["role"]),
                content=str(msg["content"]),
                seq=seq,
            ))
    db.commit()
    return {"ok": True}


# ---------------------------------------------------------------------------
# Snapshot endpoints
# ---------------------------------------------------------------------------

class SnapshotCreateRequest(BaseModel):
    name: str
    files: List[Dict[str, str]]


@app.post("/api/sessions/{session_id}/snapshots", status_code=201)
def create_snapshot(session_id: str, body: SnapshotCreateRequest, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    snap = DBSnapshot(
        session_id=session_id,
        name=body.name.strip() or "Untitled",
        files_json=json.dumps(body.files),
    )
    db.add(snap)
    db.commit()
    db.refresh(snap)
    return {
        "id": snap.id,
        "name": snap.name,
        "created_at": snap.created_at.isoformat() if snap.created_at else None,
        "file_count": len(body.files),
    }


@app.get("/api/sessions/{session_id}/snapshots")
def list_snapshots(session_id: str, db: DBSessionORM = Depends(get_db)):
    session = db.get(DBSession, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return [
        {
            "id": s.id,
            "name": s.name,
            "created_at": s.created_at.isoformat() if s.created_at else None,
            "files": json.loads(s.files_json),
        }
        for s in session.snapshots
    ]


@app.delete("/api/sessions/{session_id}/snapshots/{snapshot_id}", status_code=204)
def delete_snapshot(session_id: str, snapshot_id: int, db: DBSessionORM = Depends(get_db)):
    snap = db.query(DBSnapshot).filter(
        DBSnapshot.id == snapshot_id, DBSnapshot.session_id == session_id
    ).first()
    if not snap:
        raise HTTPException(status_code=404, detail="Snapshot not found")
    db.delete(snap)
    db.commit()


# ---------------------------------------------------------------------------
# Chat endpoints
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    message: str
    history: List[Dict[str, str]]
    code_context: str
    provider: str = "openai"
    current_module: Optional[str] = None


def _format_history(history: List[Dict[str, str]]):
    return [
        ("human" if m["role"] in ("human", "user") else "ai", m["content"])
        for m in history
    ]


def _enrich_context(code_context: str, current_module: Optional[str]) -> str:
    """Appends current curriculum module info to the code context."""
    if not current_module:
        return code_context
    module = get_module_by_id(current_module)
    if not module:
        return code_context
    return (
        code_context
        + f"\n\n[CURRICULUM MODULE: {module['title']}]"
        + f"\nObjective: {module['objective']}"
        + f"\nProject: {module['project']}"
    )


@app.post("/api/tutor/chat/stream")
@limiter.limit("20/minute")
async def stream_council(request: Request, body: ChatRequest):
    log.info("Stream request. Provider: %s, Module: %s", body.provider, body.current_module)
    history = _format_history(body.history)
    enriched = _enrich_context(body.code_context, body.current_module)

    async def event_generator():
        try:
            async for msg in council.stream_council_discussion(
                user_message=body.message,
                chat_history=history,
                code_context=enriched,
                provider=body.provider,
            ):
                yield f"data: {json.dumps(msg)}\n\n"
        except asyncio.CancelledError:
            pass
        finally:
            yield 'data: {"done": true}\n\n'

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"X-Accel-Buffering": "no", "Cache-Control": "no-cache"},
    )


@app.post("/api/tutor/chat")
@limiter.limit("20/minute")
async def chat_with_council(request: Request, body: ChatRequest):
    history = _format_history(body.history)
    enriched = _enrich_context(body.code_context, body.current_module)
    discussion = await council.get_council_discussion_async(
        user_message=body.message,
        chat_history=history,
        code_context=enriched,
        provider=body.provider,
    )
    return {"discussion": discussion}


# ---------------------------------------------------------------------------
# Execution helpers
# ---------------------------------------------------------------------------

def _prepare_files(payload: dict) -> list[dict]:
    """
    Normalises the WebSocket payload to a list of {name, content} dicts.
    Accepts both `{files: [...]}` (multi-file) and `{code: "..."}` (legacy).
    Also injects the matplotlib preamble into main.py.
    """
    if "files" in payload:
        files = [{"name": f["name"], "content": f["content"]} for f in payload["files"]]
    else:
        files = [{"name": "main.py", "content": payload.get("code", "")}]

    # Inject matplotlib preamble into main.py
    for f in files:
        if f["name"] == "main.py":
            f["content"] = MATPLOTLIB_PREAMBLE + f["content"]
            break

    return files


async def _install_packages_subprocess(packages: list[str], cwd: str, ws: WebSocket) -> bool:
    """Installs pip packages in the subprocess sandbox. Returns True on success."""
    pkg_list = ", ".join(packages[:5]) + ("..." if len(packages) > 5 else "")
    await ws.send_json({"trace": {"step": "Package Install", "detail": f"pip install {pkg_list}"}})
    try:
        result = await asyncio.to_thread(
            subprocess.run,
            [sys.executable, "-m", "pip", "install", "--quiet", "--disable-pip-version-check", *packages],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode != 0:
            await ws.send_json({"error": f"pip install failed:\n{result.stderr}", "status": "error"})
            return False
        await ws.send_json({"output": f"[Installed: {', '.join(packages)}]\n"})
        return True
    except subprocess.TimeoutExpired:
        await ws.send_json({"error": "pip install timed out (60s)", "status": "error"})
        return False


def _write_to_tmpdir(files: list[dict]) -> str:
    """Writes files to a fresh temp directory and returns its path."""
    tmp_dir = tempfile.mkdtemp()
    for f in files:
        dest = os.path.join(tmp_dir, f["name"])
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as fp:
            fp.write(f["content"])
    return tmp_dir


def _classify_line(line: str, is_error: bool) -> dict:
    stripped = line.rstrip()
    if not is_error and PLOT_MARKER in stripped:
        return {"type": "plot", "text": stripped.split(PLOT_MARKER, 1)[1]}
    return {"type": "error" if is_error else "output", "text": line}


async def _send_queue_msg(ws: WebSocket, msg: dict) -> None:
    t = msg["type"]
    if t == "plot":
        await ws.send_json({"plot": msg["text"]})
    elif t == "error":
        await ws.send_json({"error": msg["text"]})
    else:
        await ws.send_json({"output": msg["text"]})


async def _execute_subprocess(
    files: list[dict],
    ws: WebSocket,
    packages: list[str] | None = None,
    mode: str = "run",
) -> None:
    tmp_dir = _write_to_tmpdir(files)
    try:
        if packages:
            ok = await _install_packages_subprocess(packages, tmp_dir, ws)
            if not ok:
                return

        if mode == "test":
            test_files = [f["name"] for f in files if f["name"].startswith("test_") or f["name"].endswith("_test.py")]
            if not test_files:
                await ws.send_json({"error": "No test files found. Create files named test_*.py to run tests.", "status": "error"})
                return
            cmd = [sys.executable, "-m", "pytest", "-v", "--tb=short", "--no-header", "-p", "no:cacheprovider"]
        else:
            main_path = os.path.join(tmp_dir, "main.py")
            if not os.path.exists(main_path):
                await ws.send_json({"error": "No main.py found in project files.", "status": "error"})
                return
            cmd = [sys.executable, "-u", main_path]

        process = subprocess.Popen(
            cmd,
            cwd=tmp_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            encoding="utf-8",
            errors="replace",
        )

        out_queue: queue.Queue = queue.Queue()

        def read_stream(stream, is_error: bool = False):
            for line in iter(stream.readline, ""):
                if line:
                    out_queue.put(_classify_line(line, is_error))
            stream.close()

        t_out = threading.Thread(target=read_stream, args=(process.stdout,), daemon=True)
        t_err = threading.Thread(target=read_stream, args=(process.stderr, True), daemon=True)
        t_out.start()
        t_err.start()

        deadline = asyncio.get_event_loop().time() + EXECUTION_TIMEOUT_SECONDS
        timed_out = False

        while t_out.is_alive() or t_err.is_alive() or not out_queue.empty():
            if asyncio.get_event_loop().time() > deadline:
                process.kill()
                timed_out = True
                break
            try:
                await _send_queue_msg(ws, out_queue.get_nowait())
            except queue.Empty:
                await asyncio.sleep(0.05)

        t_out.join(timeout=2)
        t_err.join(timeout=2)
        process.wait()

        if timed_out:
            await ws.send_json({"error": f"\nExecution timed out after {EXECUTION_TIMEOUT_SECONDS}s.", "status": "error"})
        elif process.returncode != 0:
            await ws.send_json({"error": f"\nProcess exited with code {process.returncode}"})
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


async def _execute_docker(
    files: list[dict],
    ws: WebSocket,
    packages: list[str] | None = None,
    mode: str = "run",
) -> None:
    import docker  # noqa: PLC0415
    client = docker.from_env()
    out_queue: asyncio.Queue = asyncio.Queue()
    loop = asyncio.get_event_loop()
    container = None
    tmp_dir = None

    if packages:
        pkg_list = ", ".join(packages[:5]) + ("..." if len(packages) > 5 else "")
        await ws.send_json({"trace": {"step": "Package Install", "detail": f"pip install {pkg_list}"}})

    def stream_logs():
        nonlocal container, tmp_dir
        try:
            tmp_dir = _write_to_tmpdir(files)

            if mode == "test":
                test_files = [f["name"] for f in files if f["name"].startswith("test_") or f["name"].endswith("_test.py")]
                if not test_files:
                    loop.call_soon_threadsafe(out_queue.put_nowait, ("error", "No test files found. Create files named test_*.py to run tests."))
                    return
                if packages:
                    run_cmd = f"pip install -q {' '.join(packages)} && python -m pytest -v --tb=short --no-header -p no:cacheprovider"
                else:
                    run_cmd = "pip install -q pytest && python -m pytest -v --tb=short --no-header -p no:cacheprovider"
            else:
                main_path = os.path.join(tmp_dir, "main.py")
                if not os.path.exists(main_path):
                    loop.call_soon_threadsafe(out_queue.put_nowait, ("error", "No main.py found."))
                    return
                if packages:
                    run_cmd = f"pip install -q {' '.join(packages)} && python -u /sandbox/main.py"
                else:
                    run_cmd = "python -u /sandbox/main.py"

            # Use network access only when packages need installing; disable otherwise
            network = "bridge" if (packages or mode == "test") else "none"

            container = client.containers.run(
                DOCKER_IMAGE,
                ["sh", "-c", run_cmd],
                volumes={tmp_dir: {"bind": "/sandbox", "mode": "ro"}},
                mem_limit="128m",
                nano_cpus=500_000_000,
                network_mode=network,
                remove=False,
                detach=True,
                stdout=True,
                stderr=True,
            )
            for chunk in container.logs(stream=True, follow=True):
                line = chunk.decode("utf-8", errors="replace")
                stripped = line.rstrip()
                if PLOT_MARKER in stripped:
                    b64 = stripped.split(PLOT_MARKER, 1)[1]
                    loop.call_soon_threadsafe(out_queue.put_nowait, ("plot", b64))
                else:
                    loop.call_soon_threadsafe(out_queue.put_nowait, ("output", line))
            result = container.wait()
            loop.call_soon_threadsafe(out_queue.put_nowait, ("done", result["StatusCode"]))
        except Exception as e:
            loop.call_soon_threadsafe(out_queue.put_nowait, ("error", str(e)))
        finally:
            if tmp_dir:
                shutil.rmtree(tmp_dir, ignore_errors=True)
            if container:
                try:
                    container.remove(force=True)
                except Exception:
                    pass

    thread = threading.Thread(target=stream_logs, daemon=True)
    thread.start()

    deadline = loop.time() + EXECUTION_TIMEOUT_SECONDS
    timed_out = False

    while True:
        remaining = max(0.1, deadline - loop.time())
        try:
            msg_type, msg_data = await asyncio.wait_for(out_queue.get(), timeout=remaining)
        except asyncio.TimeoutError:
            timed_out = True
            if container:
                try:
                    container.kill()
                except Exception:
                    pass
            break

        if msg_type == "done":
            if msg_data != 0:
                await ws.send_json({"error": f"\nProcess exited with code {msg_data}"})
            break
        elif msg_type == "error":
            await ws.send_json({"error": msg_data, "status": "error"})
            break
        elif msg_type == "plot":
            await ws.send_json({"plot": msg_data})
        else:
            await ws.send_json({"output": msg_data})

    thread.join(timeout=2)
    if timed_out:
        await ws.send_json({"error": f"\nExecution timed out after {EXECUTION_TIMEOUT_SECONDS}s.", "status": "error"})


# ---------------------------------------------------------------------------
# Voice tutor WebSocket
# ---------------------------------------------------------------------------

def _transcribe_audio(audio_bytes: bytes) -> str:
    from openai import OpenAI  # noqa: PLC0415
    oai = OpenAI()
    with tempfile.NamedTemporaryFile(suffix=".webm", delete=False) as tmp:
        tmp.write(audio_bytes)
        tmp_path = tmp.name
    try:
        with open(tmp_path, "rb") as f:
            result = oai.audio.transcriptions.create(model="whisper-1", file=f)
        return result.text.strip()
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def _synthesize_speech(text: str) -> bytes:
    from openai import OpenAI  # noqa: PLC0415
    oai = OpenAI()
    return oai.audio.speech.create(model="tts-1", voice="nova", input=text).content


@app.websocket("/ws/voice-tutor")
async def voice_tutor_endpoint(websocket: WebSocket):
    await websocket.accept()
    log.info("Voice Tutor WebSocket connected")
    try:
        while True:
            audio_bytes = await websocket.receive_bytes()
            if not audio_bytes:
                continue
            log.info("Received audio: %d bytes", len(audio_bytes))
            try:
                transcription = await asyncio.to_thread(_transcribe_audio, audio_bytes)
            except Exception as e:
                log.warning("Whisper failed: %s", e)
                continue
            if not transcription:
                continue
            log.info("Transcribed: %s", transcription)
            await websocket.send_json({"role": "human", "content": transcription})

            discussion = await council.get_council_discussion_async(
                user_message=transcription,
                chat_history=[],
                code_context="Socratic Studio Voice Mode",
                provider="openai",
            )
            tutor_response = next(
                (m["content"] for m in discussion if m["role"] == "Tutor"),
                "I'm listening...",
            )
            await websocket.send_json({"role": "Tutor", "content": tutor_response})
            try:
                audio_out = await asyncio.to_thread(_synthesize_speech, tutor_response)
                await websocket.send_bytes(audio_out)
            except Exception as e:
                log.warning("TTS failed: %s", e)
    except WebSocketDisconnect:
        log.info("Voice Tutor disconnected")
    except Exception as e:
        log.exception("Voice WebSocket error: %s", e)
        await websocket.close()


# ---------------------------------------------------------------------------
# Code execution WebSocket
# ---------------------------------------------------------------------------

@app.websocket("/ws/execute")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            try:
                payload = json.loads(data)
            except json.JSONDecodeError:
                await websocket.send_json({"error": "Invalid JSON payload", "status": "error"})
                continue

            files = _prepare_files(payload)
            packages: list[str] = [p.strip() for p in payload.get("packages", []) if p.strip()]
            mode: str = payload.get("mode", "run")

            await websocket.send_json({"status": "running"})
            await websocket.send_json({"trace": {"step": "Initialization", "detail": "Allocating sandbox resources..."}})
            await asyncio.sleep(0.3)
            if mode == "test":
                await websocket.send_json({"trace": {"step": "Test Discovery", "detail": "Scanning for test_*.py files..."}})
            else:
                await websocket.send_json({"trace": {"step": "Static Analysis", "detail": "Validating python syntax and imports..."}})
            await asyncio.sleep(0.4)

            if DOCKER_AVAILABLE:
                await websocket.send_json({"trace": {"step": "Environment Boot", "detail": "Launching isolated Docker container..."}})
                await asyncio.sleep(0.3)
                try:
                    await _execute_docker(files, websocket, packages=packages, mode=mode)
                except Exception:
                    log.exception("Docker execution failed; falling back to subprocess")
                    await _execute_subprocess(files, websocket, packages=packages, mode=mode)
            else:
                await websocket.send_json({"trace": {"step": "Environment Boot", "detail": "Loading virtual environment and dependencies..."}})
                await asyncio.sleep(0.3)
                try:
                    await _execute_subprocess(files, websocket, packages=packages, mode=mode)
                except Exception:
                    log.exception("Sandbox execution failure")
                    await websocket.send_json({
                        "error": "The execution sandbox encountered an unexpected issue. Please try again.",
                        "status": "error",
                    })

            await websocket.send_json({"status": "completed"})

    except WebSocketDisconnect:
        log.info("Execution client disconnected")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
